version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

  app:
    image: python:3.10-slim
    command: python3 -m http.server 5000
    ports:
      - "5000:5000"
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app

